changelog_type: 'pull_request'
header_prefix: 'Version:'
include_unlabeled_changes: true
unlabeled_group_title: 'Other Changes'
group_config:
  - title: Bug Fixes
    labels:
      - bug
  - title: Code Improvements
    labels:
      - refactoring
  - title: New Features
    labels:
      - enhancement
  - title: Documentation Updates
    labels:
      - documentation
  - title: Dependencies Updates
    labels:
      - dependencies